# Generated by Django 5.2.1 on 2025-05-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_time',
            field=models.DurationField(blank=True, help_text='Movie duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='userrating',
            name='watch_time',
            field=models.DurationField(blank=True, help_text='Time spent watching the movie', null=True),
        ),
    ]
